# Generated by Django 6.0.1 on 2026-05-29 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeddingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=5)),
                ('image', models.ImageField(upload_to='products/')),
                ('top', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toy.category')),
            ],
        ),
        migrations.CreateModel(
            name='WeddingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=5)),
                ('image', models.ImageField(upload_to='products/')),
                ('top', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toy.weddingcategory')),
            ],
        ),
    ]
